### ISSUE TITLE
Please launch this app via Canvas.

### ISSUE THREAD

**Issue by kevincolten** [harvard-edtech/caccl#11]
@gabeabrams

I am getting a `Please launch this app via Canvas.` error when trying to launch from within the course. I don't see any logs anywhere to describe the issue. Any troubleshooting ideas?

**Comment by gabeabrams** [comment]
The starter app shows this error if the user has not launched the app via Canvas, so this error that you're getting is expected and valid.

CACCL comes with a simple and easy way to simulate launches from Canvas (check out docs on "developer mode"). I'd recommend trying that out.

**Comment by kevincolten** [comment]
Is launching the app within a canvas course via the sidebar in the iframe not launching via Canvas?

**Comment by gabeabrams** [comment]
Yes, that does count as launching via Canvas.

If you're launching via "actual" Canvas, just one warning: many browsers do not allow user sessions in iframes. Thus, if you are launching the tool in an iframe, the user's session may not be saved and the app will think that the user has not launched. This is an issue in general, not specifically for LTI or CACCL-based apps, but it's still quite relevant.

For my apps, I launch the apps in a new tab just because I don't want to have to keep track of which browsers/versions have this security constraint. I believe that right now, Safari, Chrome, and soon also Firefox have this restriction.

**Comment by kevincolten** [comment]
After a lot of toying around, I was only able to get it working when launching the tool from a matching subdomain to the canvas instance. This may help someone who is self-hosting.
