### ISSUE TITLE
Integration with express API server app

### ISSUE THREAD

**Issue by adamtyoung** [harvard-edtech/caccl#3]
Hello,
 This is more of a 'hopefully you can point me in the right direction' query, but I have an Express API app that I built that I would like to integrate with your CACCL app. The API allows me to authenticate users with JWT and get / post content via MongoDB. I would like to use this in conjunction with CACCL to build a React client that allows Canvas users to create content etc. What would be the best way to integrate with your CACCL app? Thanks again.

**Comment by gabeabrams** [comment]
You might want to take a look at the "Manual Set Up" section in the caccl docs. The main requirement that caccl has is that your app uses express-session. If your JWT-based session handling is done through express-session, you should be all set!

**Comment by gabeabrams** [comment]
The long story short is just that you can pass in `app` as a config option if you don't want caccl to create its own app.

**Comment by adamtyoung** [comment]
Do you mean something like this? 

```const initCACCL = require('caccl/server');

const app = initCACCL({
    canvasHost: 'canvas.myschool.edu',
    developerCredentials: secureConfig.developerCredentials,
    installationCredentials: secureConfig.installationCredentials,
    app: './server.js'
});
```
Thanks

**Comment by adamtyoung** [comment]
Perhaps some use case examples with code could be added to the docs? I imagine most users of this tool would also require some sort of third-party storage for created content (ie a mongo database etc).

**Comment by gabeabrams** [comment]
I believe I'm a bit confused about your question. 

If you're trying to create code that writes to a database, you should look up documentation elsewhere. There are many resources out there on how to connect with mongo databases in Node.

If you're trying to store the user's session in a mongo database instead of in memory (as caccl does), I'll point you to the documentation for express-session. You will need to create your own express app, add mongo-based express-session to that app, then pass it into CACCL (see the example below).

If you already have an express app that you want to add caccl to, just add it as follows:

```js
initCACCL({
  app: myExpressApp,
});
```

Remember, your express app needs to have express-session enabled.
